HTCTest/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HTCTest.Models
{
    public class Contact
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [Required]
        public string Patronymic { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Birthdate { get; set; }

        public string Firm { get; set; }

        public string Rank { get; set; }

        public virtual ICollection<Phone> Phones { get; set; }

        [Display(Name = "E-mails")]
        public virtual ICollection<EMail> EMails { get; set; }

        public virtual ICollection<Skype> Skypes { get; set; }

        [Display(Name = "Other contacts")]
        public virtual ICollection<OtherContact> OtherContacts { get; set; }

        public Contact()
        {
            Phones = new List<Phone>();
            EMails = new List<EMail>();
            Skypes = new List<Skype>();
            OtherContacts = new List<OtherContact>();
        }
    }
}

HTCTest/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HTCTest.Models
{
    public class ContactViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [Required]
        public string Patronymic { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Birthdate { get; set; }

        public string Firm { get; set; }

        public string Rank { get; set; }

        public IList<Phone> Phones { get; set; }

        public IList<EMail> EMails { get; set; }

        public IList<Skype> Skypes { get; set; }

        public IList<OtherContact> OtherContacts { get; set; }

        public ContactViewModel()
        {
            Phones = new List<Phone>();
            EMails = new List<EMail>();
            Skypes = new List<Skype>();
            OtherContacts = new List<OtherContact>();
        }
    }
}

HTCTest/Controllers/ContactsController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using HTCTest.Models;

namespace HTCTest.Controllers
{
    public class ContactsController : Controller
    {
        private readonly IRepository<Contact> _repository = new ContactsRepository();

        public ActionResult Index(string searchString)
        {
            ViewBag.SearchString = "";
            if (string.IsNullOrEmpty(searchString))
                return View(_repository.GetAll().ToList());
            DateTime date;
            bool isDate = DateTime.TryParseExact(searchString, "yyyy-MM-dd", DateTimeFormatInfo.CurrentInfo,
                DateTimeStyles.None, out date);

            ViewBag.SearchString = searchString;
            var searchResult = _repository.GetAll().Where(c =>
                    c.FirstName.Equals(searchString) ||
                    c.LastName.Equals(searchString) ||
                    c.Patronymic.Equals(searchString) ||
                    isDate && c.Birthdate.Equals(date) ||
                    c.Phones.Select(p => p.Number).Contains(searchString) ||
                    c.EMails.Select(e => e.Address).Contains(searchString) ||
                    c.Skypes.Select(s => s.Login).Contains(searchString) ||
                    c.OtherContacts.Select(oc => oc.Value).Contains(searchString) ||
                    c.Firm.Equals(searchString) ||
                    c.Rank.Equals(searchString))
                .ToList();
            return View(searchResult);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = _repository.Get(id.Value);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "Id,FirstName,LastName,Patronymic,Birthdate,Firm,Rank,Phones,EMails,Skypes,OtherContacts")]
            ContactViewModel contactViewModel)
        {
            if (ModelState.IsValid)
            {
                Mapper.Initialize(cfg => cfg.CreateMap<ContactViewModel, Contact>());
                var contact = Mapper.Map<ContactViewModel, Contact>(contactViewModel);
                _repository.Add(contact);
                return RedirectToAction("Index");
            }
            return View(contactViewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = _repository.Get(id.Value);
            if (contact == null)
            {
                return HttpNotFound();
            }
            Mapper.Initialize(cfg => cfg.CreateMap<Contact, ContactViewModel>()
                .ForMember("Phones", opt => opt.MapFrom(src => src.Phones.ToList()))
                .ForMember("EMails", opt => opt.MapFrom(src => src.EMails.ToList()))
                .ForMember("Skypes", opt => opt.MapFrom(src => src.Skypes.ToList()))
                .ForMember("OtherContacts", opt => opt.MapFrom(src => src.OtherContacts.ToList())));
            var contactViewModel = Mapper.Map<Contact, ContactViewModel>(contact);
            return View(contactViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "Id,FirstName,LastName,Patronymic,Birthdate,Firm,Rank,Phones,EMails,Skypes,OtherContacts")]
            ContactViewModel contactViewModel)
        {
            if (ModelState.IsValid)
            {
                Mapper.Initialize(cfg => cfg.CreateMap<ContactViewModel, Contact>());
                var contact = Mapper.Map<ContactViewModel, Contact>(contactViewModel);
               _repository.Update(contact);
                return RedirectToAction("Index");
            }
            return View(contactViewModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = _repository.Get(id.Value);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return PartialView(contact);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = _repository.Get(id);
            if (contact == null)
                return HttpNotFound();
            _repository.Remove(id);


            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HTCTest/Views/Contacts/Create.cshtml
@model HTCTest.Models.ContactViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
    <h4>Contact</h4>
    <hr/>
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Patronymic, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Patronymic, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.Patronymic, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Birthdate, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Birthdate, new {htmlAttributes = new {@class = "form-control datepicker"}})
            @Html.ValidationMessageFor(model => model.Birthdate, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Firm, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Firm, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.Firm, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rank, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rank, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.Rank, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group contact-form-group">
        @Html.LabelFor(model => model.Phones, new {@class = "control-label col-md-2"})
        <div class="col-md-offset-2">
            @if (Model?.Phones != null)
            {
                for (int i = 0; i < Model.Phones.Count; ++i)
                {
                    <div class="col-md-10 editor" data-index="@i">
                        <div class="form-inline">
                            @Html.HiddenFor(model => model.Phones[i].Id, new {id = ""})
                            @Html.EditorFor(model => model.Phones[i].Number,
                                new {htmlAttributes = new {@class = "form-control", id = ""}})
                            <input type="button" class="btn btn-default btn-remove" value="Remove phone"/>
                        </div>
                        @Html.ValidationMessageFor(model => model.Phones[i].Number, "", new {@class = "text-danger"})
                        <div class="form-group"></div>
                    </div>
                }
            }
            <div class="col-md-10 editor pattern" hidden="">
                <div class="form-inline">
                    @Html.EditorFor(model => model.Phones[-1].Number,
                        new {htmlAttributes = new {@class = "form-control", id = "", disabled = "true"}})
                    <input type="button" class="btn btn-default btn-remove" value="Remove phone"/>
                </div>
                @Html.ValidationMessageFor(model => model.Phones[-1].Number, "", new {@class = "text-danger"})
                <div class="form-group"></div>
            </div>
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.Phones)
            </div>
            <div class="col-md-10">
                <input type="button" class="btn btn-default btn-add" value="Add phone"/>
            </div>
        </div>
    </div>

    <div class="form-group contact-form-group">
        @Html.LabelFor(model => model.EMails, new {@class = "control-label col-md-2"})
        <div class="col-md-offset-2">
            @if (Model?.EMails != null)
            {
                for (int i = 0; i < Model.EMails.Count; ++i)
                {
                    <div class="col-md-10 editor" data-index="@i">
                        <div class="form-inline">
                            @Html.HiddenFor(model => model.EMails[i].Id, new {id = ""})
                            @Html.EditorFor(model => model.EMails[i].Address,
                                new {htmlAttributes = new {@class = "form-control", id = ""}})
                            <input type="button" class="btn btn-default btn-remove" value="Remove e-mail"/>
                        </div>
                        @Html.ValidationMessageFor(model => model.EMails[i].Address, "", new {@class = "text-danger"})
                        <div class="form-group"></div>
                    </div>
                }
            }
            <div class="col-md-10 editor pattern" hidden="">
                <div class="form-inline">
                    @Html.EditorFor(model => model.EMails[-1].Address,
                        new {htmlAttributes = new {@class = "form-control", id = "", disabled = "true"}})
                    <input type="button" class="btn btn-default btn-remove" value="Remove e-mail"/>
                </div>
                @Html.ValidationMessageFor(model => model.EMails[-1].Address, "", new {@class = "text-danger"})
                <div class="form-group"></div>
            </div>
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.EMails)
            </div>
            <div class="col-md-10">
                <input type="button" class="btn btn-default btn-add" value="Add e-mail"/>
            </div>
        </div>
    </div>

    <div class="form-group contact-form-group">
        @Html.LabelFor(model => model.Skypes, new {@class = "control-label col-md-2"})
        <div class="col-md-offset-2">
            @if (Model?.Skypes != null)
            {
                for (int i = 0; i < Model.Skypes.Count; ++i)
                {
                    <div class="col-md-10 editor" data-index="@i">
                        <div class="form-inline">
                            @Html.HiddenFor(model => model.Skypes[i].Id, new {id = ""})
                            @Html.EditorFor(model => model.Skypes[i].Login,
                                new {htmlAttributes = new {@class = "form-control", id = ""}})
                            <input type="button" class="btn btn-default btn-remove" value="Remove skype"/>
                        </div>
                        @Html.ValidationMessageFor(model => model.Skypes[i].Login, "", new {@class = "text-danger"})
                        <div class="form-group"></div>
                    </div>
                }
            }
            <div class="col-md-10 editor pattern" hidden="">
                <div class="form-inline">
                    @Html.EditorFor(model => model.Skypes[-1].Login,
                        new {htmlAttributes = new {@class = "form-control", id = "", disabled = "true"}})
                    <input type="button" class="btn btn-default btn-remove" value="Remove skype"/>
                </div>
                @Html.ValidationMessageFor(model => model.Skypes[-1].Login, "", new {@class = "text-danger"})
                <div class="form-group"></div>
            </div>
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.Skypes)
            </div>
            <div class="col-md-10">
                <input type="button" class="btn btn-default btn-add" value="Add skype"/>
            </div>
        </div>
    </div>

    <div class="form-group contact-form-group">
        @Html.LabelFor(model => model.OtherContacts, new {@class = "control-label col-md-2"})
        <div class="col-md-offset-2">
            @if (Model?.OtherContacts != null)
            {
                for (int i = 0; i < Model.OtherContacts.Count; ++i)
                {
                    <div class="col-md-10 editor" data-index="@i">
                        <div class="form-inline">
                            @Html.HiddenFor(model => model.OtherContacts[i].Id, new {id = ""})
                            @Html.EditorFor(model => model.OtherContacts[i].Value,
                                new {htmlAttributes = new {@class = "form-control", id = ""}})
                            <input type="button" class="btn btn-default btn-remove" value="Remove contact"/>
                        </div>
                        @Html.ValidationMessageFor(model => model.OtherContacts[i].Value, "", new {@class = "text-danger"})
                        <div class="form-group"></div>
                    </div>
                }
            }
            <div class="col-md-10 editor pattern" hidden="">
                <div class="form-inline">
                    @Html.EditorFor(model => model.OtherContacts[-1].Value,
                        new {htmlAttributes = new {@class = "form-control", id = "", disabled = "true"}})
                    <input type="button" class="btn btn-default btn-remove" value="Remove contact"/>
                </div>
                @Html.ValidationMessageFor(model => model.OtherContacts[-1].Value, "", new {@class = "text-danger"})
                <div class="form-group"></div>
            </div>
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.OtherContacts)
            </div>
            <div class="col-md-10">
                <input type="button" class="btn btn-default btn-add" value="Add contact"/>
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary"/>
        </div>
    </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).ready(function() {
            function updateIndex(element, oldIndex, newIndex) {
                element.attr("data-index", newIndex);
                element.find('input[name]').each(function(i) {
                    var oldName = $(this).attr('name');
                    var newName = oldName.replace(oldIndex, newIndex);
                    $(this).attr('name', newName);
                });
                element.find('span').each(function() {
                    var oldValMsg = $(this).attr('data-valmsg-for');
                    var newValMsg = oldValMsg.replace(oldIndex, newIndex);
                    $(this).attr('data-valmsg-for', newValMsg);
                });
            }


            $('.contact-form-group').each(function() {
                var root = $(this);
                var count = root.find('.editor').length - 1;

                function removeEvent(button) {
                    var elem = button.parent().parent();
                    var index = parseInt(elem.attr('data-index'), 10);
                    for (var i = index + 1; i < count; i++) {
                        var editor = root.find('.editor[data-index="' + i + '"]');
                        updateIndex(editor, i, i - 1);
                    }
                    elem.remove();
                    count--;
                }

                root.find('.btn-remove').click(function() {
                    removeEvent($(this));
                });

                root.find('.btn-add').click(function() {

                        var block = root.find('.pattern').clone();
                        block.removeClass('pattern');
                        block.removeAttr('id');
                        block.removeAttr('hidden');
                        block.find('input').removeAttr('disabled');
                        updateIndex(block, '-1', count.toString());
                        block.find('.btn-remove').click(function() {
                            removeEvent($(this));
                        });
                        root.find('.pattern').before(block);
                        var form = $('form');
                        form.removeData('validator');
                        form.removeData('unobtrusiveValidation');
                        $.validator.unobtrusive.parse(form);
                        count = count + 1;
                    }
                );
            });
        });
    </script>
}

HTCTest/Views/Contacts/Delete.cshtml
@model HTCTest.Models.Contact

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@($"{Model.FirstName} {Model.LastName} {Model.Patronymic}")</h4>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color text-center">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

HTCTest/Views/Contacts/Details.cshtml
@model HTCTest.Models.Contact

@{
    ViewBag.Title = "Details";
}


<div>
    <h2>Details</h2>
    <h4>Contact</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patronymic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patronymic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model=>model.Phones)
        </dt>

        <dd>
            @foreach (var phone in Model.Phones)
            {
                <div>@phone.Number</div>
            }

        </dd>

        <dt>
            @Html.DisplayNameFor(model=>model.EMails)
        </dt>

        <dd>
                @foreach (var email in Model.EMails)
                {
                    <div>@email.Address</div>
                }

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skypes)
        </dt>


        @foreach (var skype in Model.Skypes)
        {
            <dd>
                <div>@skype.Login</div>
            </dd>
        }


        <dt>
            @Html.DisplayNameFor(model => model.OtherContacts)
        </dt>

        <dd>
                @foreach (var contact in Model.OtherContacts)
                {
                   <div>@contact.Value</div>
                }
        </dd>

    </dl>


</div>

<p>
    @Html.ActionLink("Edit", "Edit", new {id = Model.Id}) |
    @Html.ActionLink("Back to List", "Index")
</p>

HTCTest/Views/Contacts/Index.cshtml
@model IEnumerable<HTCTest.Models.Contact>

@{
    ViewBag.Title = "Index";
}

<h2>Contacts</h2>

<p>
    @Html.ActionLink("Create new", "Create", "Contacts")
</p>

<form method="get" class="form-inline">
    <input name="searchString" class="form-control" value="@ViewBag.SearchString"/>
    <input type="submit" class="btn btn-default" value="Search"/>
</form>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th></th>
    </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patronymic)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit",  new { id = item.Id }) |
                @Html.ActionLink("Details", "Details",  new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", "Contacts", new { id=item.Id },
                    new { @class = "view-dialog",  data_dialog_title = "Delete" })
            </td>
        </tr>
    }

</table>